import { Dices, Shield } from "lucide-react";
import { StepButton } from "./ui";

export default function Attributes({ character, update, attributes, pointCosts, races, modifier }) {
  const spent = Object.values(character.attrs).reduce((sum, value) => sum + (pointCosts[value] ?? 0), 0);
  const racial = races.find((item) => item.id === character.race)?.bonus || "Escolha uma raça para aplicar os bônus na ficha";
  const change = (key, raw) => { const value = Math.max(8, Math.min(15, Number(raw) || 8)); const next = { ...character.attrs, [key]: value }; if (Object.values(next).reduce((sum, entry) => sum + pointCosts[entry], 0) <= 27) update({ attrs: next }); };
  const roll = () => { let next; do { next = Object.fromEntries(attributes.map(([key]) => [key, Math.max(8, Math.min(15, Array.from({ length: 4 }, () => Math.ceil(Math.random() * 6)).sort((a, b) => a - b).slice(1).reduce((a, b) => a + b, 0)))])); } while (Object.values(next).reduce((sum, value) => sum + pointCosts[value], 0) > 27); update({ attrs: next }); };
  return <><div className="attribute-tools"><div><strong>{spent}/27 pontos usados</strong><span>{27 - spent} pontos restantes · valores-base de 8 a 15</span></div><StepButton icon={Dices} onClick={roll}>Rolar 4d6 válido</StepButton></div><div className={`callout point-buy-guide ${spent === 27 ? "complete" : ""}`}><Dices size={17} /><span>{spent === 27 ? "Distribuição completa. Você já pode continuar para a próxima etapa." : "Distribua exatamente 27 pontos entre os seis atributos para desbloquear a próxima etapa."}</span></div><div className="callout racial"><Shield size={17} /><span>{racial}. Bônus raciais entram no cálculo final, sem consumir pontos do point buy.</span></div><div className="attributes">{attributes.map(([key, label]) => <div className="attribute" key={key}><span>{label}<small>Custo {pointCosts[character.attrs[key]]}</small></span><div className="attribute-control"><button type="button" aria-label={`Diminuir ${label}`} onClick={() => change(key, character.attrs[key] - 1)} disabled={character.attrs[key] <= 8}>-</button><strong>{character.attrs[key]}</strong><button type="button" aria-label={`Aumentar ${label}`} onClick={() => change(key, character.attrs[key] + 1)} disabled={character.attrs[key] >= 15 || spent >= 27}>+</button></div><strong>{modifier(character.attrs[key]) >= 0 ? `+${modifier(character.attrs[key])}` : modifier(character.attrs[key])}</strong></div>)}</div></>;
}
